export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS : "REMOVED_SELECTED_PRODUCTS",
    CART_PRODUCTS : "CART_PRODUCTS"
};